### ISSUE TITLE
Escoger licencia

### ISSUE THREAD

**Issue by marioortizmanero** [UNIZAR-30226-2021-07/documentacion#16]
Todos los proyectos open source deberían tener una licencia disponible, para que, en caso de que alguien reuse ese código, sepa de qué maneras puede usarlo para seguir los principios de los creadores. Recuerdo que es algo que recomendaban en el pdf original de la asignatura.

Las más famosas que conozco son las dos siguientes, sin entrar en gran detalle porque son un rollo:

* MIT (permisivo): básicamente establece que aquel que use el software puede hacer lo que quiera con él, incluido copiar, modificar, publicar, o incluso redistribuir, posiblemente por costes económicos para beneficio de la empresa. El creador no es responsable de nada que pueda ocasionar la nueva distribución.
* GPLv3 (copyleft): una licencia más restrictiva que establece que, principalmente, aquel que use el software, puede hacer lo que quiera con él, siempre que este usuario lo distribuya de forma open-source también, bajo la misma licencia o una similar. Por lo demás, es más o menos igual.

Hay muchos más detalles aquí por si queréis más info: https://choosealicense.com/

CC/ @xzebra @FCanfran @jmarindiez @Tomenos18 @Leticia-23 porque en verdad es para todos los repos del proyecto

**Comment by marioortizmanero** [comment]
En mi opinión deberíamos usar GPLv3 porque es un proyecto completo. Si alguien realiza una copia de un proyecto y la distribuye de cualquier otra forma, con posibles mejoras, ¿qué menos que también lo comparta para los demás, como hicieron los creadores originales? Aunque admitidamente es un poco restrictiva, promueve algo el open-source y la colaboración entre desarrolladores, que obviamente nunca está mal.

La MIT la suelo usar más bien para librerías para que realmente puedan ser usadas por cualquiera. Pero me gustaría oir más opiniones.

**Comment by jmarindiez** [comment]
Yo voto por GPLv3. Si alguien tiene que sacar beneficio somos nosotros.

**Comment by marioortizmanero** [comment]
Notar que con GPLv3 igualmente se puede sacar beneficio. La diferencia es que la entidad que lo haga tendrá que publicar su código de forma open-source y con la misma licencia o similar.

**Comment by xzebra** [comment]
GPLv3 porque está feo que privaticen tu trabajo y saquen beneficio de él.

**Comment by FCanfran** [comment]
GPLv3, por lo que habéis dicho, totalmente de acuerdo.

**Comment by Tomenos18** [comment]
Me parece bien la GPLv3

**Comment by Leticia-23** [comment]
También veo bien GPLv3 porque si nosotros lo dejamos para que se use, el que venga después que haga lo mismo.
