### ISSUE TITLE
Definir método de autenticación

### ISSUE THREAD

**Issue by marioortizmanero** [UNIZAR-30226-2021-07/documentacion#18]
Tenía que haber planteado anteriormente las maneras de autenticación. Al usar una REST API [no se puede guardar el estado](https://stackoverflow.com/questions/3105296/if-rest-applications-are-supposed-to-be-stateless-how-do-you-manage-sessions), como sucede en el caso de webs HTML dinámicas. Hay que tener en cuenta que se tienen dos APIs diferentes, una convencional con JSON, y otra con websockets (que sí que puede guardar estado), pero el mínimo común denominador es que no se puede guardar.

He encontrado varios recursos que lo explican en detalle:

* https://stackoverflow.com/questions/65520316/for-a-rest-api-can-i-use-authentication-mechanism-provided-by-flask-login-or-do
* https://stackoverflow.com/questions/47892413/how-to-secure-a-rest-api-on-flask
* https://blog.miguelgrinberg.com/post/restful-authentication-with-flask

Las opciones, de forma resumida, son las siguientes:

* Enviando siempre el usuario y la contraseña
* Mediante tokens (JWTs, OAuth). Es lo recomendado por básicamente todas las guías que he encontrado online. Existen varios tutoriales para las tecnologías que estamos usando, aunque parecen algo más complejos. Pero ya se puede ver que el código del backend está casi todo en el tutorial, y hay una librería que lo facilita considerablemente. Es más que nada el concepto.
  * Flask: https://realpython.com/token-based-authentication-with-flask/
  * React: https://jasonwatmore.com/post/2019/04/06/react-jwt-authentication-tutorial-example
  * Flutter: https://flutter.dev/docs/cookbook/networking/authenticated-requests

Tras leer sobre esto puedo ver que realmente no hay mucho entre lo que escoger, principalmente JWTs con `flask-jwt`. Tendré que detallarlo en la memoria, pero esto sirve como resumen y discusión al respecto.

**Comment by xzebra** [comment]
No se si estás planteando un problema o simplemente estás diciendo las tecnologías. 

Los puristas de REST te dirán que la autenticación es estado, pero REST es simplemente una filosofía para hacer APIs, ni la mejor ni la peor. Podemos incluir perfectamente autenticación que no morirá ningún gatito.

**Comment by xzebra** [comment]
Por otro lado, me parece obvio el uso de un token de sesión y la manera más recomendable.

Ahora bien, el tema de los websockets no lo has abordado y era el único que me preocupaba. Se pueden usar websockets en el frontend en flutter?

**Comment by marioortizmanero** [comment]
Para los websockets la autenticación puede ser de la misma forma, con JWTs. El hecho de que tenga estado no implica que tengamos que hacer uso de él para la autenticación, y probablemente lo más fácil será tener un único método. [Este artículo](https://dev.to/kleeut/authenticating-websockets-21lo) lo describe bastante bien, podemos:

* Hacer un mensaje de autenticación explícito. Se enviaría al principio y cuando vaya a expirar. Yo diría que la opción más natural.
* Incluir la autenticación en cada mensaje. Posiblemente más fácil de implementar pero más costoso en banda ancha y tiempo de procesamiento.

También se tendrá que notificar al usuario cuando caduque o vaya a caducar su token. Es curioso porque no se puede hacer como con el REST API, en cuyo caso el endpoint devolvería un error de "401 Unauthorized" por ejemplo; con websockets no tiene por qué recibirse una respuesta directa a un mensaje. Esto se puede hacer de varias formas también según el artículo, pero la única que me parece viable es el mensaje que le indique al usuario que se va a expirar su token.

Y Flutter permite usar websockets sin problemas. Aquí incluyo un artículo oficial:

https://flutter.dev/docs/cookbook/networking/web-sockets

Y aquí otro tutorial para React:

https://dev.to/finallynero/using-websockets-in-react-4fkp
