### ISSUE TITLE
Definir restricciones de registro

### ISSUE THREAD

**Issue by marioortizmanero** [UNIZAR-30226-2021-07/documentacion#20]
Restricciones a decidir:

- [ ] Longitud minima de nombre de usuario
- [ ] Caracteres permitidos en nombre de usuario (espacios? ascii raro como →?)
- [ ] Longitud minima de contraseña

Si me he dejado alguno hacedmelo saber

**Comment by xzebra** [comment]
Yo propongo:
- Longitud mínima: 4 caracteres
- Longitud máxima: 12 caracteres
- Caracteres especiales permitidos para el nombre: _
- Longitud mínima de contraseña: 6 u 8 caracteres

**Comment by marioortizmanero** [comment]
Cerrado por #27.
