### ISSUE TITLE
Plan Gestión - 3.1.3. Procesos técnicos

### ISSUE THREAD

**Issue by Leticia-23** [UNIZAR-30226-2021-07/documentacion#5]

**Comment by xzebra** [comment]
¿A qué se refiere con esto?

**Comment by Leticia-23** [comment]
Está en el pdf de las instrucciones del plan de gestión. Pero basicamente:
Describir los métodos, herramientas y técnicas necesarios tanto para construir el software (p.ej.
herramientas de desarrollo) como para desplegarlo y probarlo.
